2024-06-08 13:14:58,616 Exception on /maya/profile [GET] [in /home/mokeira/.local/lib/python3.8/site-packages/flask/app.py:828]
Traceback (most recent call last):
  File "/home/mokeira/.local/lib/python3.8/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mokeira/.local/lib/python3.8/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mokeira/.local/lib/python3.8/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mokeira/.local/lib/python3.8/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/mokeira/.local/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/mnt/c/Users/user/Desktop/Folders/software_development/chapter_13_pagination/app/routes.py", line 71, in profile
    error_out=False)
  File "/home/mokeira/.local/lib/python3.8/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/mokeira/.local/lib/python3.8/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/mokeira/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/mokeira/.local/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/mnt/c/Users/user/Desktop/Folders/software_development/chapter_13_pagination/app/templates/profile.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/mnt/c/Users/user/Desktop/Folders/software_development/chapter_13_pagination/app/templates/base.html", line 68, in top-level template code
    {% block content %}
  File "/mnt/c/Users/user/Desktop/Folders/software_development/chapter_13_pagination/app/templates/profile.html", line 43, in block 'content'
    { %for post in posts %}
  File "/home/mokeira/.local/lib/python3.8/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2024-06-08 13:14:58,889 Exception on /maya/profile [GET] [in /home/mokeira/.local/lib/python3.8/site-packages/flask/app.py:828]
Traceback (most recent call last):
  File "/home/mokeira/.local/lib/python3.8/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mokeira/.local/lib/python3.8/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mokeira/.local/lib/python3.8/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mokeira/.local/lib/python3.8/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/mokeira/.local/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/mnt/c/Users/user/Desktop/Folders/software_development/chapter_13_pagination/app/routes.py", line 71, in profile
    error_out=False)
  File "/home/mokeira/.local/lib/python3.8/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/mokeira/.local/lib/python3.8/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/mokeira/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/mokeira/.local/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/mnt/c/Users/user/Desktop/Folders/software_development/chapter_13_pagination/app/templates/profile.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/mnt/c/Users/user/Desktop/Folders/software_development/chapter_13_pagination/app/templates/base.html", line 68, in top-level template code
    {% block content %}
  File "/mnt/c/Users/user/Desktop/Folders/software_development/chapter_13_pagination/app/templates/profile.html", line 43, in block 'content'
    { %for post in posts %}
  File "/home/mokeira/.local/lib/python3.8/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2024-06-08 13:15:35,971 Tinker Full-Stack App [in /mnt/c/Users/user/Desktop/Folders/software_development/chapter_13_pagination/app/__init__.py:49]
2024-06-08 13:15:40,889 Tinker Full-Stack App [in /mnt/c/Users/user/Desktop/Folders/software_development/chapter_13_pagination/app/__init__.py:49]
2024-06-17 15:26:43,247 Tinker Full-Stack App [in /mnt/c/Users/user/Desktop/Folders/software_development/chapter_13_pagination/app/__init__.py:49]
2024-06-17 15:26:52,366 Tinker Full-Stack App [in /mnt/c/Users/user/Desktop/Folders/software_development/chapter_13_pagination/app/__init__.py:49]
2024-06-17 15:43:01,482 Tinker Full-Stack App [in /mnt/c/Users/user/Desktop/Folders/software_development/chapter13_pagination_assesment/app/__init__.py:49]
2024-06-17 15:43:04,666 Tinker Full-Stack App [in /mnt/c/Users/user/Desktop/Folders/software_development/chapter13_pagination_assesment/app/__init__.py:49]
2024-06-17 15:43:44,754 Tinker Full-Stack App [in /mnt/c/Users/user/Desktop/Folders/software_development/chapter13_pagination_assesment/app/__init__.py:49]
2024-06-17 15:43:48,963 Tinker Full-Stack App [in /mnt/c/Users/user/Desktop/Folders/software_development/chapter13_pagination_assesment/app/__init__.py:49]
2024-06-18 16:28:47,515 Tinker Full-Stack App [in /mnt/c/Users/user/Desktop/Folders/software_development/chapter13_pagination_assesment/app/__init__.py:49]
2024-06-18 16:29:08,232 Tinker Full-Stack App [in /mnt/c/Users/user/Desktop/Folders/software_development/chapter13_pagination_assesment/app/__init__.py:49]
2024-06-18 17:33:13,329 Tinker Full-Stack App [in /mnt/c/Users/user/Desktop/Folders/software_development/chapter13_pagination_assesment/app/__init__.py:49]
2024-06-18 17:37:39,261 Tinker Full-Stack App [in /mnt/c/Users/user/Desktop/Folders/software_development/chapter13_pagination_assesment/app/__init__.py:49]
2024-06-18 17:39:18,662 Exception on / [GET] [in /home/mokeira/.local/lib/python3.8/site-packages/flask/app.py:828]
Traceback (most recent call last):
  File "/home/mokeira/.local/lib/python3.8/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mokeira/.local/lib/python3.8/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mokeira/.local/lib/python3.8/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mokeira/.local/lib/python3.8/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/mokeira/.local/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/mnt/c/Users/user/Desktop/Folders/software_development/chapter13_pagination_assesment/app/routes.py", line 31, in index
    return render_template('index.html',
  File "/home/mokeira/.local/lib/python3.8/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/mokeira/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/mokeira/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/mokeira/.local/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/mokeira/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "/home/mokeira/.local/lib/python3.8/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/mokeira/.local/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/mnt/c/Users/user/Desktop/Folders/software_development/chapter13_pagination_assesment/app/templates/index.html", line 58, in template
    {% sort_by current_user_posts %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'sort_by'. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
